[package]
name = "bmatch"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { varsion = "2.0.28", features = ["full"] }
proc-macro2 = "1.0.66"
quote = "1.0.32"
peeking_take_while = "1.0.0"